name: Build and execute tests

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Restore pre requeties
              run: dotnet workload restore

            - name: Restore Packages
              run: dotnet restore KalanalyzeCode.ConfigurationManager.sln

            - name: Build Solution
              run: dotnet build KalanalyzeCode.ConfigurationManager.sln --no-restore -c Release

            - name: Execute Tests
              run: dotnet test KalanalyzeCode.ConfigurationManager.sln --no-build -c Release
