name: Build and execute tests

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Set .NetSdk version
              uses: actions/setup-dotnet@v4
              with:
                global-json-file: global.json
                
            - name: Set environment variable for NuGet signature verification
              run: echo "DOTNET_NUGET_SIGNATURE_VERIFICATION=false" >> $GITHUB_ENV

            - name: Restore pre requeties
              run: dotnet workload restore

            - name: Restore Packages
              run: dotnet restore KalanalyzeCode.ConfigurationManager.sln

            - name: Build Solution
              run: dotnet build KalanalyzeCode.ConfigurationManager.sln --no-restore -c Release

            - name: Install playwright browsers
              shell: pwsh
              working-directory: tests/Ui.AcceptanceTesting
              run: ./bin/Release/net8.0/playwright.ps1 install

            - name: Execute Tests
              run: dotnet test KalanalyzeCode.ConfigurationManager.sln --no-build -c Release --collect:"XPlat Code Coverage"
            
            - name: Upload Coverage to Codecov
              uses: codecov/codecov-action@v3
              with: 
                token: ${{ secrets.CODECOV_TOKEN }}
                files: ./TestResults/**/*.xml
                flags: unittests
                name: codecov-umbrella

